var simplemaps_countrymap_mapdata = {
  main_settings: {
    //General settings
    width: '600', //'700' or 'responsive'
    background_color: '#837f7f',
    background_transparent: 'yes',
    border_color: '#ffffff',

    //State defaults
    state_description: 'State description',
    state_color: '#88A4BC',
    state_hover_color: '#3B729F',
    state_url: '',
    border_size: '1.5',
    all_states_inactive: 'no',
    all_states_zoomable: 'yes',

    //Location defaults
    location_description: 'Location description',
    location_url: '',
    location_color: '#FF0067',
    location_opacity: '0.4',
    location_hover_opacity: 1,
    location_size: 25,
    location_type: 'square',
    location_image_source: 'frog.png',
    location_border_color: '#FFFFFF',
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: 'no',
    all_locations_hidden: 'no',

    //Label defaults
    label_color: '#d5ddec',
    label_hover_color: '#d5ddec',
    label_size: 22,
    label_font: 'Arial',
    hide_labels: 'no',
    hide_eastern_labels: 'no',

    //Zoom settings
    zoom: 'yes',
    manual_zoom: 'yes',
    back_image: 'no',
    initial_back: 'no',
    initial_zoom: '-1',
    initial_zoom_solo: 'no',
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: 'yes',
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    //Popup settings
    popup_color: 'white',
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: '12px/1.5 Verdana, Arial, Helvetica, sans-serif',
    popup_nocss: 'no',

    //Advanced settings
    div: 'map',
    auto_load: 'yes',
    url_new_tab: 'yes',
    images_directory: 'default',
    fade_time: 0.1,
    link_text: 'View Website',
    popups: 'detect',
    state_image_url: '',
    state_image_position: '',
    location_image_url: '',
    border_hover_color: '#fbfbfb',
  },
  state_specific: {
    ECU1266: {
      name: 'Azuay',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1267: {
      name: 'El Oro',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1268: {
      name: 'Loja',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1269: {
      name: 'Zamora Chinchipe',
      color: '#df814c',
      hover_color: '#dd6624',
      description: 'Circunscripción consular de Nueva Loja',
    },
    ECU1270: {
      name: 'Galápagos',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1277: {
      name: 'Bolivar',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1278: {
      name: 'Cañar',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1279: {
      name: 'Cotopaxi',
      color: '#ba6eac',
      hover_color: '#b3399d',
      description: 'Circunscripción consular de Quito',
    },
    ECU1280: {
      name: 'Guayas',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1281: {
      name: 'Los Rios',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1282: {
      name: 'Manabi',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU1284: {
      name: 'Chimborazo',
      color: '#ba6eac',
      hover_color: '#b3399d',
      description: 'Circunscripción consular de Tulcan',
    },
    ECU1285: {
      name: 'Morona Santiago',
      color: '#df814c',
      hover_color: '#dd6624',
      description: 'Circunscripción consular de Nueva Loja',
    },
    ECU1286: {
      name: 'Orellana',
      color: '#df814c',
      hover_color: '#dd6624',
      description: 'Circunscripción consular de Nueva Loja',
    },
    ECU1287: {
      name: 'Pichincha',
      color: '#ba6eac',
      hover_color: '#b3399d',
      description: 'Circunscripción consular de Tulcan',
    },
    ECU1288: {
      name: 'Pastaza',
      color: '#df814c',
      hover_color: '#dd6624',
      description: 'Circunscripción consular de Nueva Loja',
    },
    ECU1289: {
      name: 'Napo',
      color: '#ba6eac',
      hover_color: '#b3399d',
      description: 'Circunscripción consular de Tulcan',
    },
    ECU1290: {
      name: 'Tungurahua',
      color: '#ba6eac',
      hover_color: '#b3399d',
      description: 'Circunscripción consular de Tulcan',
    },
    ECU1335: {
      name: 'Esmeraldas',
      color: '#6e94ba',
      hover_color: '#3172b3',
      description: 'Circunscripción consular de Esmeraldas',
    },
    ECU1409: {
      name: 'Carchi',
      color: '#e65151',
      hover_color: '#e62a2a',
      description: 'Circunscripción consular de Tulcann',
    },
    ECU1410: {
      name: 'Imbabura',
      color: '#e65151',
      hover_color: '#e62a2a',
      description: 'Circunscripción consular de Tulcann',
    },
    ECU1411: {
      name: 'Sucumbios',
      color: '#df814c',
      hover_color: '#dd6624',
      description: 'Circunscripción consular de Nueva Loja',
    },
    ECU5507: {
      name: 'Santa Elena',
      color: '#76c078',
      hover_color: '#48bd4b',
      description: 'Circunscripción consular de Guayaquil',
    },
    ECU5508: {
      name: 'Santo Domingo de los Tsáchilas',
      color: '#ddc86b',
      hover_color: '#d9b40f',
    },
  },
  locations: {
    0: {
      lat: '-0.194568',
      lng: '-78.493005',
      name: 'Quito',
      size: '6',
      type: 'circle',
      color: '#676767',
      description: 'Capital de Ecuador',
    },
  },
  labels: {},
  legend: {
    entries: [],
  },
  regions: {},
};
